/* Run against tests/fixtures/router.php; Google is always intercepted. */
const assert = require('node:assert/strict');
const {chromium} = require('playwright');
const AxeBuilder = require('@axe-core/playwright').default;
const base = 'http://127.0.0.1:8765';
(async () => {
	const browser = await chromium.launch({headless: true});
	let checks = 0;
	const ok = (value, message) => { assert(value, message); checks++; process.stdout.write('PASS: ' + message + '\n'); };
	const context = await browser.newContext();
	let enterpriseLoads = 0;
	await context.route('https://www.google.com/recaptcha/enterprise.js*', route => {
		enterpriseLoads++;
		return route.fulfill({contentType: 'application/javascript', body: `window.grecaptcha = window.grecaptcha || {}; window.grecaptcha.enterprise = {ready: fn => fn(), execute: async (key, options) => { window.fixtureExecutions = (window.fixtureExecutions || 0) + 1; if (window.fixtureFail) throw new Error('fixture'); return (window.fixtureMode || 'valid') + ':' + crypto.randomUUID(); }};`});
	});
	const page = await context.newPage();
	const errors = []; page.on('pageerror', error => errors.push(error.message));
	await page.goto(base + '/qa/unrelated/');
	ok(await page.locator('script[src*="comment-protection"]').count() === 0, 'Unrelated page has no protection script');
	await page.goto(base + '/');
	ok(await page.locator('.mrn-recaptcha-comment').count() === 1, 'Guest form gets one protection field');
	ok(enterpriseLoads === 0, 'Google script is deferred until submission');
	const a11y = await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
	ok(a11y.violations.length === 0, 'Blog form passes axe WCAG A/AA');
	await page.screenshot({path: '/tmp/mrn-recaptcha-qa-20261001/reports/blog-form.png', fullPage: true});
	await page.locator('#comment').fill('Preserve my comment');
	await page.locator('#author').fill('Fixture'); await page.locator('#email').fill('fixture@example.test');
	await page.evaluate(() => { window.fixtureFail = true; });
	await page.locator('#submit').click();
	await page.waitForFunction(() => document.querySelector('.mrn-recaptcha-status').textContent.includes('could not verify'));
	ok(await page.locator('#comment').inputValue() === 'Preserve my comment', 'Provider failure preserves comment text');
	ok(await page.locator('.mrn-recaptcha-status').evaluate(e => e === document.activeElement), 'Failure feedback receives keyboard focus');
	const errorA11y = await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
	ok(errorA11y.violations.length === 0, 'Failure state passes axe');
	await page.screenshot({path: '/tmp/mrn-recaptcha-qa-20261001/reports/browser-error.png', fullPage: true});
	await page.evaluate(() => {
		window.fixtureFail = false;
		window.capturedTokens = [];
		document.querySelector('form').addEventListener('submit', e => { e.preventDefault(); window.capturedTokens.push(new FormData(e.target).get('mrn_recaptcha_token')); });
	});
	await page.locator('#submit').click(); await page.waitForFunction(() => window.capturedTokens.length === 1);
	await page.locator('#submit').click(); await page.waitForFunction(() => window.capturedTokens.length === 2);
	const tokens = await page.evaluate(() => window.capturedTokens);
	ok(tokens[0] && tokens[1] && tokens[0] !== tokens[1], 'Every retry obtains a fresh token');
	ok(enterpriseLoads === 1, 'Retries share one Enterprise script');
	ok(await page.locator('[name="mrn_recaptcha_token"]').inputValue() === '', 'Token cleared after intercepted AJAX submission');
	await page.goto(base + '/qa/multiple/');
	await page.evaluate(() => {
		window.grecaptcha = {execute: () => 'legacy-wpforms-kept'};
		window.captured = [];
		document.querySelectorAll('form').forEach(form => {
			form.querySelector('textarea').value = 'Multiple form fixture';
			form.querySelector('[name="author"]').value = 'Fixture';
			form.querySelector('[name="email"]').value = 'fixture@example.test';
			form.addEventListener('submit', e => { e.preventDefault(); window.captured.push(new FormData(form).get('mrn_recaptcha_token')); });
		});
	});
	await page.locator('#submit').click(); await page.waitForFunction(() => window.captured.length === 1);
	await page.locator('#second-submit').click(); await page.waitForFunction(() => window.captured.length === 2);
	ok(await page.evaluate(() => window.captured[0] !== window.captured[1]), 'Multiple forms receive independent tokens');
	ok(await page.evaluate(() => window.grecaptcha.execute() === 'legacy-wpforms-kept'), 'Existing legacy/WPForms API is preserved');
	ok(await page.locator('script[src*="enterprise.js"]').count() === 1, 'Multiple forms share one Enterprise loader');
	await page.evaluate(() => {
		const original = document.querySelector('form'); const clone = original.cloneNode(true); clone.id = 'dynamic';
		clone.addEventListener('submit', e => { e.preventDefault(); window.dynamicToken = new FormData(clone).get('mrn_recaptcha_token'); });
		document.querySelector('main').appendChild(clone); clone.requestSubmit();
	});
	await page.waitForFunction(() => !!window.dynamicToken);
	ok(true, 'Dynamically inserted form protected by delegation');
	await page.goto(base + '/qa/mixed/');
	ok(await page.locator('#commentform [data-action="mrn_blog_comment"]').count() === 1 && await page.locator('#second-commentform [data-action="mrn_product_review"]').count() === 1, 'Mixed forms bind to their own post IDs, independent of the page query');
	await page.goto(base + '/qa/product/');
	ok(await page.locator('[data-action="mrn_product_review"]').count() === 1, 'Logged-in purchaser review form has protection');
	const reviewA11y = await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
	ok(reviewA11y.violations.length === 0, 'WooCommerce review form passes axe WCAG A/AA');
	await page.screenshot({path: '/tmp/mrn-recaptcha-qa-20261001/reports/review-form.png', fullPage: true});
	await page.goto(base + '/qa/admin/');
	ok(await page.locator('.mrn-recaptcha-comment').count() === 0, 'Administrator form is exempt');
	await page.goto(base + '/');
	await page.locator('#comment').fill('Native form submit bypass fixture ' + Date.now());
	await page.locator('#author').fill('Fixture'); await page.locator('#email').fill('fixture@example.test');
	const [rejection] = await Promise.all([page.waitForNavigation(), page.evaluate(() => HTMLFormElement.prototype.submit.call(document.querySelector('form')))]);
	const rejectedBody = await page.locator('body').innerText();
	ok(rejection.status() === 403 && rejectedBody.includes('Your submission was not saved'), 'Native form.submit bypass is rejected with HTTP 403');
	ok(errors.length === 0, 'No browser JavaScript errors');
	await page.screenshot({path: '/tmp/mrn-recaptcha-qa-20261001/reports/server-error.png', fullPage: true});
	const blocked = await browser.newContext();
	await blocked.route('https://www.google.com/recaptcha/enterprise.js*', route => route.abort());
	const offline = await blocked.newPage(); await offline.goto(base + '/');
	await offline.locator('#comment').fill('Offline fixture'); await offline.locator('#author').fill('Fixture'); await offline.locator('#email').fill('fixture@example.test');
	await offline.locator('#submit').click();
	await offline.waitForFunction(() => document.querySelector('.mrn-recaptcha-status').textContent.includes('could not verify'));
	ok(await offline.locator('#comment').inputValue() === 'Offline fixture', 'Blocked Google loader fails accessibly without losing text');
	const nojs = await browser.newContext({javaScriptEnabled: false}); const nojsPage = await nojs.newPage(); await nojsPage.goto(base + '/');
	ok(await nojsPage.locator('noscript').innerText().then(t => t.includes('JavaScript is required')), 'No-JavaScript requirement is visible');
	await browser.close();
	process.stdout.write(`PASS: ${checks} browser assertions.\n`);
})().catch(error => { process.stderr.write(error.stack + '\n'); process.exit(1); });
